name: Pull-request tracking
on:
  pull_request:
    types: [opened, reopened]

jobs:
  steps:
    - name: Check WIP in PR Title
      uses: embano1/wip@v1
      with:
        title: "${{ github.event.pull_request.title }}"
        regex: "^[[:space:]]*(WIP)+(:)*"

  if: success()
  triage:
    permissions:
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/labeler@v4
        with:
          repo-token: ${{ secrets.SECRET_ISSUE }}
