name: "Issue check"

on:
  workflow_call:
    inputs:
      REPO_PATH:
        type: string
        required: true
      ISSUE_TITLE:
        type: string
        required: true
      ISSUE_BODY:
        type: string
        required: true

jobs:
  get-length:
    runs-on: ubuntu-latest
    outputs:
      title: ${{ steps.getLength.outputs.title_length }}
      body: ${{ steps.getLength.outputs.body_length }}
    steps:
      - name: Get length
        run: |
          PREPARED_TITLE=$(echo $inputs.TITLE | sed 's/ //g; s/\[bug\]//; s/\[Bug\]//; s/\[BUG\]//')
          echo "::set_output name=title_length::${#PREPARED_TITLE}"
          echo "::set_output name=body_length::${#BODY}"

  comment-issuess:
    needs: get-length
    if: 'needs.get-length.title < 5 || needs.get-length.body < 5'
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
        - name: Label issue
          uses: andymckay/labeler@e6c4322d0397f3240f0e7e30a33b5c5df2d39e90
          with:
           add-labels: "WIP"

        - name: Comment issue
          uses: KeisukeYamashita/create-comment@v1
          with:
            comment: Please check that the issue is described correctly. The name should reflect the meaning
            of the issue. The body of the issue should contain a description of the problem and code
            to reproduce it. You can use the issue [template]( ${{ inputs.REPO_PATH }} ) to make it easy.