name: Label issues
on:
  issues:
    types:
      - reopened
      - opened

jobs:
  label_issues:
    PREPAREDTITLE=${github.event.issue.title//\[BUG\]/}
    PREPAREDTITLE=${github.event.issue.title//BUG/}
    PREPAREDTITLE=${PREPAREDTITLE// /}
    echo ${#PREPAREDTITLE}
    if: ${#PREPAREDTITLE} < 4
    uses: KristinaZoteva/counter-actions-test/.github/workflows/check_issues.yaml@main
    with:
      REPO_PATH: 'https://github.com/KristinaZoteva/counter-actions-test/issues/new'
    secrets:
      SECRET_ISSUES: ${{ secrets.SECRET_ISSUE }}