name: "Issue comment"

on:
  issues:
    types:
      - reopened
      - opened
jobs:
  get-length:
    runs-on: ubuntu-latest
    outputs:
      output1: ${{ steps.getLength.outputs.title_length }}
    steps:
      - name: get title length
        id: getLength
        env:
          TITLE: ${{ github.event.issue.title }}
          PREPARED_TITLE: $env.TITLE | sed 's/ //g; s/\[bug\]//; s/\[Bug\]//; s/\[BUG\]//'
        run: |
          echo"::set_output name=title_length::${env.PREPARED_TITLE}"


  comment-issue:
    if: 'needs.get-length.output1.title_length < 5'
    uses: KristinaZoteva/counter-actions-test/.github/workflows/check_issues.yaml@main
    with:
      REPO_PATH: 'https://github.com/KristinaZoteva/counter-actions-test/issues/new'
    secrets:
      SECRET_ISSUES: ${{ secrets.SECRET_ISSUE }}