name: "Issue comment"

on:
  issues:
    types:
      - reopened
      - opened
jobs:
  get-length:
    runs-on: ubuntu-latest
    outputs:
      output1: ${{ steps.getLength.outputs.title_length }}
    steps:
      - name: get title length
        id: getLength
        run: |
          TITLE=${{ github.event.issue.title }}
          echo $TITLE
          TITLE2=${TITLE//\[\w+\]/}
          echo $TITLE2
          PREPARED_TITLE=${TITLE// /}
          echo $PREPARED_TITLE
          TITLE_LENGTH=${#PREPARED_TITLE}
          echo $TITLE_LENGTH
          echo"::set_output name=title_length::${TITLE_LENGTH}"

  comment-issue:
    if: 'needs.get-length.output1.title_length < 5'
    uses: KristinaZoteva/counter-actions-test/.github/workflows/check_issues.yaml@main
    with:
      REPO_PATH: 'https://github.com/KristinaZoteva/counter-actions-test/issues/new'
    secrets:
      SECRET_ISSUES: ${{ secrets.SECRET_ISSUE }}