name: Pull-request tracking
on:
  pull_request_target:
    types:
      - labeled
      - unlabeled
      - opened
      - edited
      - reopened
      - converted_to_draft
      - ready_for_review

jobs:
  label_pull_request:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - name: Label pull request
        if: contains(github.event.pull_request.title, 'WIP') || contains(github.event.pull_request.labels.*.name, 'WIP')
        uses: andymckay/labeler@e6c4322d0397f3240f0e7e30a33b5c5df2d39e90
        with:
          add-labels: "new pull request"
          repo-token: ${{ secrets.SECRET_ISSUE }}
